adguard-home:
  env:
    TZ: Europe/Berlin

  service:
    main:
      primary: true
      ports:
        http:
          port: 3000

    dns-tcp:
      enabled: false
    dns-udp:
      enabled: false
