apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: {{ .Chart.Name }}-static
  namespace: {{ .Release.Namespace }}
  labels:
    kubernetes.io/service-name: {{ .Chart.Name }}-service
addressType: IPv4
ports:
  - name: http
    port: {{ .Values.valetudo.robot.port }}
    protocol: TCP
endpoints:
  - addresses:
      - {{ .Values.valetudo.robot.ip }}