apiVersion: v1
kind: Service
metadata:
  name: valetudo-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:  
  name: valetudo-service
  namespace: {{ .Release.Namespace }}
  labels:
    kubernetes.io/service-name: valetudo-service
addressType: IPv4
ports:
  - port: {{ .Values.valetudo.robot.port }}
endpoints:
  - addresses:
    - {{ .Values.valetudo.robot.ip }}