apiVersion: ha.homeassistant.io/v1
kind: HomeAssistant
metadata:
  name: {{ .Release.Name }}-home
spec:
  version: "2025.6"
  storage:
    size: 5Gi
    storageClassName: longhorn-3
  service:
    type: ClusterIP
  bootstrap:
    enabled: true
    location:
        name: {{ .Values.homeassistant.location.name }}
        latitude: {{ .Values.homeassistant.location.latitude }}
        longitude: {{ .Values.homeassistant.location.longitude }}
        elevation: {{ .Values.homeassistant.location.elevation }}
        unitSystem: {{ .Values.homeassistant.location.unitSystem }}
        currency: {{ .Values.homeassistant.location.currency }}
        timeZone: {{ .Values.homeassistant.location.timeZone }}
    credentials:
      secretRef:
        name: homeassistant-admin
    createApiToken: true