apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: mealie-sso-secrets
  namespace: default
spec:
  forceRegenerate: false
  fields:
    - fieldName: "clientId"
      encoding: "base64"
      length: "64"
    - fieldName: "clientsecret"
      encoding: "base64"
      length: "64"
