apiVersion: v1
kind: Secret
metadata:
  name: mealie-sso-secret
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "mealie-sso-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}

  {{- $clientId := (get $secretData "client-id") | default (randAlphaNum 64 | b64enc) }}
  client-id: {{ $clientId | quote }}
  {{- $clientSecret := (get $secretData "client-secret") | default (randAlphaNum 64 | b64enc) }}
  client-secret: {{ $clientSecret | quote }}