apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: longhorn-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - argocd.vadderung.niphrams-bu.de
  rules:
    - host: "argocd.vadderung.niphrams-bu.de"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: argo-cd-argocd-server
                port:
                  number: 80
