vadderung:
  baseDomain: ~

firefly-iii:
  image:
    tag: version-6.7.7

  persistence:
    storageClassName: longhorn-3

  config:
    existingSecret: default-budget-secret

    env:
      # I don't like this
      # DB_HOST_FILE: "/run/secrets/db-secret/host"
      DB_HOST: "default-budget-db-rw"
      DB_CONNECTION: "pgsql"
      DB_PORT_FILE: "/run/secrets/db-secret/port"
      DB_DATABASE_FILE: "/run/secrets/db-secret/dbname"
      DB_USERNAME_FILE: "/run/secrets/db-secret/user"
      DB_PASSWORD_FILE: "/run/secrets/db-secret/password"
      TZ: "Europe/Berlin"
      AUTHENTICATION_GUARD: "remote_user_guard"
      AUTHENTICATION_GUARD_HEADER: "Remote-User"
      AUTHENTICATION_GUARD_EMAIL: "Remote-Email"
      DB_PORT: ~
      DB_DATABASE: ~
      DB_USERNAME: ~

  extraVolumes:
  - name: db-secret
    secret:
      secretName: default-budget-db-app

  extraVolumeMounts:
  - name: db-secret
    mountPath: /run/secrets/db-secret
    readOnly: true
