apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: longhorn
  namespace: longhorn-system
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  project: default
  source:
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.8.1
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
    chart: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
