mealie:
  image: ghcr.io/mealie-recipes/mealie:v2.8.0
  replicas: 1 # Mealie doesn't play well with multiple pods
  pgsecrets: mealie-postgres-cluster-app
  timezone: Europe/Berlin
  allowSignup: false

postgres:
  instances: 1
  superuser: true # Enables superuser rights for the app user (needed to restore mealie backups)