mealie:
  image: ghcr.io/mealie-recipes/mealie@sha256:bdf17cf5d70f4aef10d5344ec128e970a888aa8a14b6c86eed866773e0108c53
  replicas: 1 # Mealie doesn't play well with multiple pods
  pgsecrets: mealie-postgres-cluster-app
  timezone: Europe/Berlin
  allowSignup: false

postgres:
  instances: 2
  superuser: true # Enables superuser rights for the app user (needed to restore mealie backups)
