apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-secret-generator
  namespace: default
spec:
  project: default
  sources:
    - chart: kubernetes-secret-generator
      repoURL: https://helm.mittwald.de
      targetRevision: 3.4.1
  destination:
    server: https://kubernetes.default.svc
    namespace: kubernetes-secret-generator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
