sources:
  chartRepo:
    url: https://github.com/niphram/vadderung
    revision: HEAD
  valuesRepo:
    url: https://github.com/niphram/vadderung-values
    revision: HEAD

spec:
  source:
    repoURL: https://github.com/niphram/vadderung

  destination:
    server: https://kubernetes.default.svc
