apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-cluster
spec:
  instances: {{ .Values.instances }}
  imageName: {{ .Values.imageName }}
  
  managed:
    roles:
    - name: app
      ensure: present
      login: true
      superuser: {{ .Values.superuser }}

  # configure storage types used
  storage:
    storageClass: {{ .Values.storage.storageClass }}
    size: {{ .Values.storage.size }}
  walStorage:
    storageClass: {{ .Values.walStorage.storageClass }}
    size: {{ .Values.walStorage.size }}

  # see https://cloudnative-pg.io/documentation/1.22/kubernetes_upgrade/
  nodeMaintenanceWindow:
    reusePVC: false # rebuild from other replica instead