apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - {{ .Values.mealie.baseURL }}
      secretName: {{ .Release.Name }}-tls
  rules:
    - host: {{ .Values.mealie.baseURL }}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mealie-app-service
                port:
                  number: 80
