apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mealie-ingress
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: "mealie.vadderung.niphrams-bu.de"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: mealie-app-service
                port:
                  number: 80
