# yaml-language-server: $schema=https://www.authelia.com/schemas/latest/json-schema/configuration.json
server:
  address: "tcp://:9091/"
  disable_healthcheck: true
authentication_backend:
  password_reset:
    disable: true
  password_change:
    disable: true
  ldap:
    address: 'ldap://ldap-service:3890'
    implementation: 'lldap'
    timeout: '5s'
    start_tls: false
    pooling:
      enable: false
      count: 5
      retries: 2
      timeout: '10 seconds'
    base_dn: '{{`{{- secret "/run/secrets/lldap-secret/base-dn" }}`}}'
    user: '{{`cn={{- secret "/run/secrets/lldap-secret/lldap-ldap-user-name" }},{{- secret "/run/secrets/lldap-secret/base-dn" }}`}}'
    password: '{{`{{- secret "/run/secrets/lldap-secret/lldap-ldap-user-pass" }}`}}'
access_control:
  default_policy: "one_factor"
identity_validation:
  reset_password:
    jwt_secret: '{{`{{- secret "/run/secrets/authelia/jwt_secret" }}`}}'
storage:
  encryption_key: '{{`{{- secret "/run/secrets/authelia/encryption_key" }}`}}'
  postgres:
    address: '{{`tcp://{{- secret "/etc/db-secret/host" }}:{{- secret "/etc/db-secret/port" }}`}}'
    database: '{{`{{- secret "/etc/db-secret/dbname" }}`}}'
    username: '{{`{{- secret "/etc/db-secret/username" }}`}}'
    password: '{{`{{- secret "/etc/db-secret/password" }}`}}'
notifier:
  filesystem:
    filename: "/data/notification.txt"
session:
  secret: '{{`{{- secret "/run/secrets/authelia/session_secret" }}`}}'
  cookies:
    - name: "authelia_session"
      domain: "{{ .Values.vadderung.baseDomain }}"
      authelia_url: "https://auth.{{ .Values.vadderung.baseDomain }}"
      expiration: "1 week"
      inactivity: "1 day"
  redis:
    host: "authelia-dragonfly-cluster"
identity_providers:
  oidc:
    hmac_secret: '{{`{{- secret "/run/secrets/oidc/hmac_secret" }}`}}'
    jwks:
      - algorithm: "RS256"
        use: sig
        key: {{`{{ secret "/run/secrets/jwks/tls.key" | mindent 10 "|" | msquote }}`}}
        certificate_chain: {{`{{ secret "/run/secrets/jwks/tls.crt" | mindent 10 "|" | msquote }}`}}
    clients:
      {{`{{ range (glob "/run/secrets/providers/*.yaml") }}
      - {{ fileContent . | indent 8 | trim }}
      {{ end }}`}}