apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: auth
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      prune: true

  sources:
    - path: apps/charts/auth
      repoURL: {{ .Values.sources.chartRepo.url }}
      targetRevision: {{ .Values.sources.chartRepo.revision }}
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: {{ .Values.sources.valuesRepo.url }}
      targetRevision: {{ .Values.sources.valuesRepo.revision }}
      ref: values
