apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: apps/charts/ingress-nginx
    repoURL: https://github.com/niphram/vadderung
    targetRevision: HEAD
