apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: longhorn-system
    server: {{ .Values.spec.destination.server }}
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
        pod-security.kubernetes.io/audit: privileged
        pod-security.kubernetes.io/warn: privileged
    automated:
      enabled: true
      prune: true

  sources:
    - path: apps/charts/longhorn
      repoURL: {{ .Values.sources.chartRepo.url }}
      targetRevision: {{ .Values.sources.chartRepo.revision }}
      helm:
        valueFiles:
          - $values/values.yaml
    - repoURL: {{ .Values.sources.valuesRepo.url }}
      targetRevision: {{ .Values.sources.valuesRepo.revision }}
      ref: values
