apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default
  destination:
    namespace: kube-system # kubeseal expects the controller to be in kube-system by default
    server: {{ .Values.spec.destination.server }}

  # ArgoCD sync options
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      enabled: true
      prune: true

  # Helm chart
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.17.7
    helm:
      valuesObject:
        fullnameOverride: sealed-secrets-controller # change name to make kubeseal easier to use
