apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "address-pool"
  namespace: {{ .Release.Namespace }}
spec:
  blocks:
  - start: "192.168.178.221"
    stop: "192.168.178.230"