apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie-deployment
spec:
  selector:
    matchLabels:
      app: mealie-app
  replicas: {{ .Values.mealie.replicas }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mealie-app
    spec:
      containers:
        - name: mealie-app
          image: {{ .Values.mealie.image }}
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /api/app/about
              port: liveness-port
            failureThreshold: 5
            periodSeconds: 10
          volumeMounts:
          - name: mealie-data
            mountPath: /app/data/
          env:
          - name: ALLOW_SIGNUP
            value: {{ .Values.mealie.allowSignup | quote }}
          - name: PUID
            value: "1000"
          - name: PGID
            value: "1000"
          - name: TZ
            value: {{ .Values.mealie.timezone | default "" }}
          - name: BASE_URL
            value: {{ .Values.mealie.baseURL | default "" }}
          # Postgres Variables
          - name: DB_ENGINE
            value: postgres
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mealie.pgsecrets }}
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mealie.pgsecrets }}
                key: password
          - name: POSTGRES_SERVER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mealie.pgsecrets }}
                key: host
          - name: POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mealie.pgsecrets }}
                key: port
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mealie.pgsecrets }}
                key: dbname
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc
---
kind: Service
apiVersion: v1
metadata:
  name: mealie-app-service
spec:
  selector:
    app: mealie-app
  ports:
    - protocol: TCP
      targetPort: 9000
      port: 80
  type: LoadBalancer