vadderung:
  baseDomain: ~

rss:
  imagePullSecrets: []
  image:
    repository: ~
    pullPolicy: IfNotPresent
    tag: latest
  service:
    port: 8000
  resources: {}

  podAnnotations:
    reloader.stakater.com/auto: "true"

  livenessProbe: ~
  #    httpGet:
  #      path: /
  #      port: http
  readinessProbe: ~
  #    httpGet:
  #      path: /
  #      port: http

  envFrom: ~
  volumeMounts: ~
  volumes: ~
