vadderung:
  baseDomain: ~

grafana:
  persistence:
    enabled: true
    type: pvc
    storageClassName: longhorn-3
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  grafana.ini:
    auth.proxy:
      enabled: true
      header_name: Remote-User
      header_property: username
      auto_sign_up: true
      headers: Name:Remote-Name Email:Remote-Email Groups:Remote-Groups
