apiVersion: gateway.envoyproxy.io/v1alpha1
kind: HTTPRouteFilter
metadata:
  name: energy-credential-injection
spec:
  credentialInjection:
    overwrite: true
    credential:
      valueRef:
        name: energy-credential