apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .Chart.Name }}-service
subsets:
- addresses:
  - ip: {{ .Values.energy.meter.ip }}
  ports:
  - name: http
    port: {{ .Values.energy.meter.port }}
    protocol: TCP