apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.energy.meter.port }}
      protocol: TCP
      targetPort: {{ .Values.energy.meter.port }}
      name: http
  clusterIP: None
  type: ClusterIP
