apiVersion: v1
kind: Secret
type: "Opaque"
metadata:
  name: {{ .Release.Name }}-adguard-home-config
  namespace: {{ .Release.Namespace }}
stringData:
  AdGuardHome.yaml: |-
    schema_version: 34
    http:
      address: 0.0.0.0:80

    dns:
      bind_hosts:
        - 0.0.0.0
      port: 53
      upstream_dns:
        - 1.1.1.1
        - 1.0.0.1
      bootstrap_dns:
        - 1.1.1.1
        - 1.0.0.1
      protection_enabled: true
      filtering_enabled: true

    filters:
      - enabled: true
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
        name: AdGuard DNS filter
        id: 1
      - enabled: false
        url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
        name: AdAway Default Blocklist
        id: 2

    filtering:
      rewrites:
        - domain: '*.{{ .Values.vadderung.baseDomain }}'
          answer: 192.168.178.210
          enabled: true
        - domain: fritz.box
          answer: 192.168.178.1
          enabled: true
        - domain: vadderung.{{ .Values.vadderung.baseDomain }}
          answer: 192.168.178.200
          enabled: true
        - domain: ddns.{{ .Values.vadderung.baseDomain }}
          answer: A
          enabled: true
        - domain: ddns.{{ .Values.vadderung.baseDomain }}
          answer: AAAA
          enabled: true