apiVersion: v1alpha1
kind: LinkAliasConfig
name: net0
selector:
  match: true # Only one physical interface
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: net0
clientIdentifier: mac
---
apiVersion: v1alpha1
kind: DHCPv6Config
name: net0
clientIdentifier: mac
