argo-cd:
  redis-ha:
    enabled: true
  controller:
    replicas: 1
  server:
    replicas: 2
  repoServer:
    replicas: 2
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
