# TODO: Make real secrets
domain: example.test

blueprint:
  provider:
    oidc:
      clientID:
      clientSecret:

authentik:
  global:
    env:
      - name: POSTGRES_HOST
        valueFrom:
          secretKeyRef:
            name: authentik-postgres-cluster-app
            key: host
      - name: POSTGRES_DB_NAME
        valueFrom:
          secretKeyRef:
            name: authentik-postgres-cluster-app
            key: dbname
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: authentik-postgres-cluster-app
            key: username
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: authentik-postgres-cluster-app
            key: password
      - name: POSTGRES_PORT
        valueFrom:
          secretKeyRef:
            name: authentik-postgres-cluster-app
            key: port
    envFrom:
      - secretRef:
          name: mealie-sso-secret

  authentik:
    secret_key: "PleaseGenerateA50CharKey"
    error_reporting:
      enabled: false
    postgresql:
      host: env://POSTGRES_HOST
      name: env://POSTGRES_DB_NAME
      user: env://POSTGRES_USER
      password: env://POSTGRES_PASSWORD
      port: env://POSTGRES_PORT

  server:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.178.211
    ingress:
      enabled: false
      hosts:
        - authentik.domain.tld

  postgresql:
    enabled: false

  redis:
    enabled: true

  worker:
    livenessProbe:
      timeoutSeconds: 5
    startupProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    readinessProbe:
      timeoutSeconds: 5

  blueprints:
    configMaps:
      - authentik-blueprints-configmap
    secrets:
      - mealie-blueprint

postgres:
  instances: 2
  superuser: false # Enables superuser rights for the app user
