# TODO: Make real secrets

authentik:
  authentik:
    secret_key: "PleaseGenerateA50CharKey"
    error_reporting:
      enabled: false
    postgresql:
      password: "ThisIsNotASecurePassword"

  server:
    ingress:
      enabled: false
      hosts:
        - authentik.domain.tld

  postgresql:
    enabled: false
    auth:
      password: "ThisIsNotASecurePassword"

  redis:
    enabled: false