# TODO: Make real secrets
domain: example.test

blueprint:
  provider:
    oidc:
      clientID:
      clientSecret:

authentik:
  authentik:
    secret_key: "PleaseGenerateA50CharKey"
    error_reporting:
      enabled: false
    postgresql:
      password: "ThisIsNotASecurePassword"

  server:
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.178.211
    ingress:
      enabled: false
      hosts:
        - authentik.domain.tld

  postgresql:
    enabled: true
    auth:
      password: "ThisIsNotASecurePassword"

  redis:
    enabled: true

  worker:
    livenessProbe:
      timeoutSeconds: 5
    startupProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    readinessProbe:
      timeoutSeconds: 5

  blueprints:
    configMaps:
      - authentik-blueprints-configmap
    secrets:
      - mealie-blueprint
