context: {}
entries:
- attrs:
    authentication: require_authenticated
    denied_action: message_continue
    designation: authorization
    layout: stacked
    name: Authorize Application
    policy_engine_mode: any
    title: Redirecting to %(app)s
  conditions: []
  identifiers:
    pk: ac56577e-2101-488f-8c6b-94a6ce88c522
    slug: default-provider-authorization-implicit-consent
  model: authentik_flows.flow
  permissions: []
  state: present
metadata:
  labels:
    blueprints.goauthentik.io/generated: 'true'
  name: authentik Export - 2025-06-17 15:15:47.951808+00:00
version: 1
