vadderung:
  baseDomain: ~

adguard-home:
  config:
    existingSecret: infra-dns-adguard-home-config
  persistence:
    conf:
      enabled: false
    work:
      enabled: false

  service:
    dns:
      type: LoadBalancer
      externalTrafficPolicy: Local
      annotations:
        metallb.io/loadBalancerIPs: 192.168.1.211
