vadderung:
  baseDomain: ~

adguard-home:
  config:
    existingSecret: adguard-home-secret
  persistence:
    conf:
      enabled: false
    work:
      enabled: false

  service:
    dns:
      type: LoadBalancer
      loadBalancerIP: '192.168.178.211'
      externalTrafficPolicy: Local
