apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authelia-jwk-rsa
  namespace: {{ .Release.Namespace }}
spec:
  secretName: authelia-jwk-rsa
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-cluster-issuer
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 2048
  usages:
    - digital signature
    - key encipherment
  dnsNames:
    - "auth.{{ .Values.vadderung.baseDomain }}"