apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: authelia-oidc-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  hmac_secret: {{ randAlphaNum 128 | quote }}
  jwks.key: {{ genPrivateKey "rsa" | quote }}