apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authelia-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  rules:
    - host: "auth.{{ .Values.vadderung.baseDomain }}"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: authelia-service
                port:
                  number: 80
