apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: StringSecret
metadata:
  name: lldap-secret
spec:
  forceRegenerate: false
  data:
    lldap-ldap-user-name: admin
    base-dn: dc={{ ".Values.vadderung.baseDomain" | replace "." ",dc=" }}
  fields:
    - fieldName: "lldap-jwt-secret"
      encoding: "base64"
      length: "128"
    - fieldName: "lldap-key-seed"
      encoding: "base64"
      length: "128"
    - fieldName: "lldap-ldap-user-pass"
      encoding: "base64"
      length: "128"