apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app: uptime-kuma-app
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 2
  template:
    metadata:
      {{- with .Values.uptime_kuma.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: uptime-kuma-app
    spec:
      {{- with .Values.uptime_kuma.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: uptime-kuma-app
          image: "{{ .Values.uptime_kuma.image.repository }}:{{ .Values.uptime_kuma.image.tag }}"
          imagePullPolicy: {{ .Values.uptime_kuma.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.uptime_kuma.service.port }}
              protocol: TCP
          {{- with .Values.uptime_kuma.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.uptime_kuma.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.uptime_kuma.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.uptime_kuma.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.uptime_kuma.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: uptime-kuma-app-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: uptime-kuma-app
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 80
