vadderung:
  baseDomain: ~

kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn-2
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 10Gi

  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: longhorn-2
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 2Gi

  nodeExporter:
    enabled: true

  kubeStateMetrics:
    enabled: true
