vadderung:
  baseDomain: ~

cwa:
  # dev-image from 2026/01/26
  image: ghcr.io/crocodilestick/calibre-web-automated@sha256:fed9bc09df026a2b9aa965fca6105ec2ceefee770a2ce34c0f0322224086dbfd
  tz: Europe/Berlin
  port: 8083
  storage:
    librarySize: 128Gi
    configSize: 2Gi

  # startupProbe:
  #   httpGet:
  #     port: http
  #     path: /health
  #   initialDelaySeconds: 30
  #   periodSeconds: 5
  #   timeoutSeconds: 3
  # livenessProbe:
  #   httpGet:
  #     path: /health
  #     port: http
  #   timeoutSeconds: 3
  # readinessProbe:
  #   httpGet:
  #     path: /health
  #     port: http
  #   timeoutSeconds: 3
